### PR TITLE
More linux-i686 fixin'

### PR DESCRIPTION
**Pull request by arlolra**
Seems to fix building Instantbird but then gets to,

```
Building project docker-image - 00aa6a76e278
dpkg: error: unknown option --add-architecture
```

/cc @boklm @azadi

### CODE REVIEW

**Comment by arlolra** [comment]
> dpkg: error: unknown option --add-architecture

I think that's because @azadi was missing,

```
-distribution: Ubuntu-12.04
+distribution: Debian-7.11
```

in 9979e309.

**Comment by azadi** [comment]
I think I had that. Did you confirm if adding that fixes the issue?

**Comment by arlolra** [comment]
Building now.

**Comment by arlolra** [comment]
The result of the build is https://paganini.erinn.org/~arlolra/tor-messenger/tor-messenger-0.1.0b6-linux-i686-aa54af.tar.xz

So, this patch works for linux-i686.  I'm going to build the other platforms/archs before merging though.

**Comment by boklm** [comment]
For the adding of the "dpkg --add-architecture i386" command, it can be done like in commit c0c64f886175164edf8df3f5a91c2f22fe33ace0.

**Comment by arlolra** [comment]
Thanks @boklm!

I was about to merge this since linux-x86_64 and osx builds worked too.  Let me amend.

**Comment by arlolra** [comment]
How does that look?  Good to merge?

**Comment by boklm** [comment]
Yes, looks good.

**Pull request merged**
