### PR TITLE
Bug 19816: Create mar files

### PR DESCRIPTION
**Pull request by boklm**

### CODE REVIEW

**Comment by arlolra** [comment]
This looks great.  I'm currently building f9bb482b913c6de724f74338bc921ff41b95fcf5, so won't be able to test for a little while, but feel free to merge it if you think it's ready.

**Comment by boklm** [comment]
Yes, I think it's ready, so I merged it. Thanks.

**Comment by arlolra** [comment]
Great, I'm starting a build.

**Comment by azadi** [comment]
Great work as usual @boklm, thank you! I will start a build later as well.

**Comment by arlolra** [comment]
I ran `make tor-messenger`.  This is what I see in my screen now,

```
Adding symlink add instructions to update manifests

Adding file and directory remove instructions from file 'removed-files'
/var/tmp/dist/mar-tools/make_full_update.sh: line 155: /var/tmp/dist/mar-tools/mar: No such file or directory
mv: cannot stat `tor-messenger/Browser.work/output.mar': No such file or directory

Finished
```

**Comment by arlolra** [comment]
The next lines were,

```
./rbm/rbm build tor-messenger --target tor-messenger --target windows-i686
Building project instantbird - instantbird-8d00ed48c485-windows-i686-920858
Created /tmp/rbm-4k2Vp/instantbird-8d00ed48c485.tar.gz
```

so that was after build Linux on both archs.  The output looks like,

```
~/tor-messenger-build/out/tor-messenger/tor-messenger-0.2.0b2-linux-i686-24a58f$ ls
mar-tools-linux32.zip  tor-messenger-linux32-0.2.0b2_en-US.tar.xz
~/tor-messenger-build/out/tor-messenger/tor-messenger-0.2.0b2-linux-x86_64-8c1261$ ls
mar-tools-linux64.zip  tor-messenger-linux64-0.2.0b2_en-US.mar  tor-messenger-linux64-0.2.0b2_en-US.tar.xz
```

**Comment by boklm** [comment]
Thanks for noticing this. This should be fixed by 0b7aae46a2c731abd7bac8405e4b4939ab11cea5.

**Pull request merged**
