### PR TITLE
Trac 21376: Hide timestamp/account from message selection

### PR DESCRIPTION
**Pull request by vqhuy**
Also add some missing localization for Twitter's actions (like, unlike).

### CODE REVIEW

**Comment by arlolra** [comment]
Thanks!  We're just about to tag release, then I'll take a look.

**Comment by arlolra** [comment]
I merged the localization changes in 2678bea5, thanks!

And, rebased the other changes in f36e421f.  However, when testing, these preferences show up as desired in the config editor, but don't seem to have any noticeable effect. @c633 did you test this?

**Comment by vqhuy** [comment]
I tested manually by editing the prefs in Config Editor. It worked with **user set** values but didn't work with default values. I thought that it would be straightforward but it seems like I have to patch hardcoded values in `imThemes.jsm` too (built and tested). 

I think it should be the same as `messenger.status.defaultIdleAwayMessage`, this value is set in `all-instantbird.js` and read using `getComplexValue(name, nsIPrefLocalizedString)`. Did I miss something?

**Comment by arlolra** [comment]
> Did I miss something?

I think the problem is that we're replacing a uri `chrome://chat/locale/conversations.properties` with a template `%message%`.  The call to `getLocalizedPrefWithDefault()` is probably throwing then, and just returning the default value.

The point of the uri is so that this formatting can be localized.  But we don't want that.  We should just hardcode `html = "%message%"` three times in imTheme.jsm and be done with it.

**Comment by arlolra** [comment]
New patch in e8b71bff that I'm going to try building.

**Comment by vqhuy** [comment]
Hmm, no chance for users to change these settings?

**Comment by arlolra** [comment]
> Hmm, no chance for users to change these settings?

Good point ... and, maybe I got things wrong above.

**Comment by arlolra** [comment]
> and, maybe I got things wrong above.

Nah, `Ci.nsIPrefLocalizedString` expects a uri for the default,
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/NsIPrefLocalizedString

So, I think they're two options,

1) Hardcode the template as in the patch above, but then it can't be user defined;
2) Change `prefBranch.getComplexValue` to `getCharPref()` and then set the defaults as you did in this patch, and that should preserve the user's ability to override.

**Comment by vqhuy** [comment]
> Change prefBranch.getComplexValue to getCharPref() and then set the defaults as you did in this patch, and that should preserve the user's ability to override.

I tested with a custom pref and it worked, without needing change `getComplexValue` to `getCharPref`. 

For this patch, we just need to set the defaults in `all-instantbird.js` and `imThemes.jsm` as you said but I also made changes in `conversations.properties` to get rid of confusing.

**Comment by arlolra** [comment]
> I tested with a custom pref and it worked, without needing change getComplexValue to getCharPref.

That's because `getComplexValue` does different things depending on where it's loading the default value vs a user defined one.

The reason you needed to this,

```
+       html = getLocalizedPrefWithDefault("systemMessagesTemplate",
 +-                                         "%time% - %message%");
 ++                                         "%message%");
```

is because you're hitting,

```
      } catch(e) {
        return aDefault;
      }
```

in `getLocalizedPrefWithDefault`

**Comment by vqhuy** [comment]
Ah, yes, we could avoid the exception. Thanks!

**Comment by vqhuy** [comment]
I fixed the patch in d7731f4748d667daf44baa9724f406e5e153bcb8. I kept the defaults pref in this patch instead of 0001 to align with the context. PTAL.

**Comment by vqhuy** [comment]
Close since Arlo fixed this in ce74e0c031df621fe7daf3318b81325b07890041.

**Comment by arlolra** [comment]
Yeah, sorry, I was just testing and we needed to remove `.data;`

**Comment by vqhuy** [comment]
That was my bad. Thanks for fixing it 👍 
But how did you notice that? I tested d7731f4748d667daf44baa9724f406e5e153bcb8 but it worked. I guess my build wasn't using the latest change.

**Comment by arlolra** [comment]
> I guess my build wasn't using the latest change.

Maybe not?  There was an error in the console saying that `aHTML` was undefined when I tried to copy a selection.

Anyways, all's well that ends well.  I merged ce74e0c.  Thanks @c633!

**Pull request closed without merging**
